### ISSUE TITLE
Error calling the plugin (Error 500)

### ISSUE THREAD

**Issue by razuro** [mightyhaggis/simple-gallery#1]
Hi,

First of all thank you for doing this in Monstra.

I've followed your example in http://www.mightyhaggis.com/blog/simple-gallery

and created all the slideshow snippets and block, then call the plugin in my header chunk like so:

<code><?php Simple_Gallery::get('slides','slideshow' [,'slideshow-image|slideshow-carousel'] ); ?></code>

My upload folder is 'slides'. Do I need to put the full path hard coded or just the name of the folder?

Thank you!

----
P/S: Your download example zip file is 404.

**Comment by mightyhaggis** [comment]
Hi razuro, 
Pleasure, hopefully it proves useful.

your `slides` folders should have the path `public/uploads/slides/` no need to hard code just specify the path in from `uploads/`.
Example files updated. http://www.mightyhaggis.com/blog/simple-gallery

**Comment by razuro** [comment]
Thank you for your quick attention :+1:. Unfortunately, I'm still having the error. I could not find any php or apache error log though. I'm on Windows, using MAMP, php 5.6.8. I'm resorting to normal code though (no plugin). Thank you again.
